services:
  mango:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - C:/Users/sachi/Desktop/data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mango:27017/

  frontend:
    image: mern-frontend
    ports:
      - 3000:3000
    environment:
      # Tell Frontend where the Backend is
      INTERNAL_API_URL: http://backend:4000 
    depends_on:
      - backend

  backend:
    image: mern-backend
    ports:
      - 4000:4000
    environment:
      # Tell Backend where the Database is
      MONGO_URI: mongodb://admin:qwerty@mango:27017/
      JWT_SECRET_KEY: my_super_secret_key_123
    depends_on:
      - mango